# Generated by Django 3.2 on 2022-08-25 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=100, verbose_name='Отчество')),
                ('image', models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото работника')),
                ('title', models.CharField(max_length=100, verbose_name='Должность')),
                ('hired_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата приема на работу')),
                ('salary', models.IntegerField(blank=True, null=True, verbose_name='Размер заработной платы')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee', verbose_name='Начальник')),
            ],
        ),
    ]
